/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rschall' at '03.12.15 13:31' with Gradle 2.6
 *
 * @author rschall, @date 03.12.15 13:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
